### PR TITLE
feat: get all winners

### PR DESCRIPTION
**Pull request by ghost**
`#3`
This PR extracts all the winners information from database and display it on admin site.
image

### CODE REVIEW

**Comment by iokiwi** [comment]
Thanks! Any chance it could be formatted as a vertical list?

**Comment by ghost** [comment]
> Thanks! Any chance it could be formatted as a vertical list?

Yes let me present it vertically.

**Comment by ghost** [comment]
> Thanks! Any chance it could be formatted as a vertical list?

The list is now in vertical form.

**Comment by iokiwi** [comment]
Thanks!

**Pull request merged**
